apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-service-reader-binding
  namespace: jenkins-namespace
subjects:
- kind: ServiceAccount
  name: jenkins-sa
  namespace: jenkins-namespace
roleRef:
  kind: ClusterRole
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
