apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-dind
  namespace: {{ .Values.namespace }}
  labels:
    app: jenkins-dind
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-dind
  template:
    metadata:
      labels:
        app: jenkins-dind
    spec:
      containers:
        - name: jenkins-dind
          image: {{ .Values.jenkinsDinD.image }}
          imagePullPolicy: {{ .Values.jenkinsDinD.imagePullPolicy }}
          securityContext:
            privileged: true
          ports:
            - containerPort: 2376
              name: dind
          volumeMounts:
            - name: docker-certs
              mountPath: /certs/client
          resources:
            requests:
              memory: {{ .Values.jenkinsDinD.resources.requests.memory }}
              cpu: {{ .Values.jenkinsDinD.resources.requests.cpu }}
            limits:
              memory: {{ .Values.jenkinsDinD.resources.limits.memory }}
              cpu: {{ .Values.jenkinsDinD.resources.limits.cpu }}
      volumes:
        - name: docker-certs
          emptyDir: {}
