# Use the official Nginx image from the Docker Hub
FROM nginx:alpine

# Copy the frontend static files into the appropriate directory
COPY ./app/Frontend/templates /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
