# Use the official Python image from the Docker Hub
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the backend requirements file into the container
COPY ./app/Backend/requirements.txt .

# Install any dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Flask application code into the container
COPY ./app/Backend /app

# Expose port 5000
EXPOSE 5000

# Run the application
CMD ["python", "main.py"]
