kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: 10.0.0.10
  apiServerPort: 4982
nodes:
- role: control-plane
  extraMounts:
    - hostPath: /c/data/pv-data/
      containerPath: /data/pv-data/
  extraPortMappings:
    - containerPort: 30000
      hostPort: 30000
      listenAddress: "0.0.0.0"
    - containerPort: 31000
      hostPort: 31000
      listenAddress: "0.0.0.0"
    - containerPort: 30080
      hostPort: 30080
      listenAddress: "0.0.0.0"
    - containerPort: 32100
      hostPort: 32100
      listenAddress: "0.0.0.0"
    - containerPort: 32200
      hostPort: 32200
      listenAddress: "0.0.0.0"
- role: worker
  extraMounts:
    - hostPath: /c/data/pv-data/
      containerPath: /data/pv-data/
  extraPortMappings:
    - containerPort: 30000
      hostPort: 30010
      listenAddress: "0.0.0.0"
    - containerPort: 31000
      hostPort: 31010
      listenAddress: "0.0.0.0"
    - containerPort: 30080
      hostPort: 31080
      listenAddress: "0.0.0.0"
    - containerPort: 32100
      hostPort: 32110
      listenAddress: "0.0.0.0"
    - containerPort: 32200
      hostPort: 32210
      listenAddress: "0.0.0.0"
