apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  labels:
    {{- include "argocd.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31500  # Change this to the desired nodePort value
  selector:
    {{- include "argocd.selectorLabels" . | nindent 4 }}
