apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: mongo-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.flask.image.port  }}"
    spec:
      containers:
        - name: mongo
          image: mongo:4.4
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
          resources:
            requests:
              memory: 512Mi
              cpu: "500m"
            limits:
              memory: 2Gi
              cpu: 2
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc
