# persistentvolume.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: mongo-namespace
spec:
  capacity:
    storage: {{ .Values.mongo.persistence.size }}
  accessModes:
    - {{ .Values.mongo.persistence.accessMode }}
  storageClassName: {{ .Values.mongo.persistence.storageClass }}
  hostPath:
    path: "/data/pv-data/mongodb"  # Replace with your host directory for volume storage