# persistentvolume.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: mongo-namespace
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/path/to/host/directory"  # Replace with your host directory for volume storage
---
# persistentvolumeclaim.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: mongo-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi