{{- if .Values.service }}
{{- if .Values.service.port }}
{{- if .Values.service.nodePort }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-flask-app.fullname" . }}-nodeport
  labels:
    app.kubernetes.io/name: {{ include "my-flask-app.name" . }}
    helm.sh/chart: {{ include "my-flask-app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: {{ include "my-flask-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }} # Use .Values.service.port instead of nil pointer
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }} # Use .Values.service.nodePort
{{- end }}
{{- end }}
{{- end }}
{{- define "my-flask-app.name" -}}
{{- printf "%s-%s" .Release.Name .Chart.Name | trunc 63 | trimSuffix "-" }}
{{- end }}

{{- define "my-flask-app.chart" -}}
{{- .Chart.Name }}
{{- end }}
