apiVersion: v1
entries:
  monitoring:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-06-07T16:51:58.4624844+03:00"
    description: A Helm chart for deploying Prometheus and Grafana for monitoring
    digest: ceb96af5ef4fa68e698707aba6f20d262755cd4134fea1f71408fbe17c5920ff
    name: monitoring
    type: application
    urls:
    - monitoring-0.1.0.tgz
    version: 0.1.0
generated: "2024-06-07T16:51:58.4612177+03:00"
