# Updated Prometheus configuration
prometheus:
  enabled: true
  service:
    type: NodePort
    port: 9090
    targetport: 9090
    nodePort: 32100
  persistence:
    enabled: true
    storageClass: standard
    accessMode: ReadWriteOnce
    size: 1Gi
  rbac:
    create: true
  ingress:
    enabled: false

# Updated Grafana configuration
grafana:
  enabled: true
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
    nodePort: 32200
  persistence:
    enabled: true
    storageClass: standard
    accessMode: ReadWriteOnce
    size: 1Gi
  ingress:
    enabled: false

# Define storage classes if they are not provided by default
storageClass:
  prometheus: standard
  grafana: standard

# Service account settings
serviceAccount:
  create: false