apiVersion: v1
kind: Service
metadata:
  name: combined-service
spec:
  selector:
    app: combined-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32000  # Choose any available port in your cluster
  type: NodePort