# combined-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: combined-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: combined-app
  template:
    metadata:
      labels:
        app: combined-app
    spec:
      containers:
      - name: flask-backend
        image: yourdockerhubusername/persudoku-backend:latest  # Update with your Flask backend image
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"  # Adjust memory request based on your workload
            cpu: "100m"      # Adjust CPU request based on your workload
          limits:
            memory: "512Mi"  # Adjust memory limit based on your workload
            cpu: "500m"      # Adjust CPU limit based on your workload
      - name: nginx-frontend
        image: yourdockerhubusername/persudoku-frontend:latest  # Update with your Nginx frontend image
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"  # Adjust memory request based on your workload
            cpu: "50m"       # Adjust CPU request based on your workload
          limits:
            memory: "256Mi"  # Adjust memory limit based on your workload
            cpu: "100m"      # Adjust CPU limit based on your workload
