apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring-namespace
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: {{ .Values.prometheus.nodePort }}
