apiVersion: v1
entries:
  appchart:
  - apiVersion: v2
    appVersion: "1.0"
    created: 2024-05-27T17:37:22.2828406+03:00
    description: A Helm chart for Kubernetes
    digest: "sha256:digest_value_here"
    name: appchart
    type: application
    urls:
    - http://localhost:8080/appchart-0.1.0.tgz
    version: 0.1.0
generated: "2024-05-27T17:37:22.2828406+03:00"