# Default values for your Helm chart
replicaCount:
  flask: 1
  mongodb: 1

flask:
  image:
    repository: roiyki/persudoku-flask
    pullPolicy: IfNotPresent
    tag: "latest"
  service:
    type: NodePort
    port: 5000
    nodePort: 30000
  environment:
    MONGO_URI: mongodb://mongo-service.mongo-namespace:27017/sudoku_app

mongo:
  image:
    repository: mongo
    tag: 4.4
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 27017
  persistence:
    enabled: true
    size: 1Gi
    accessMode: ReadWriteOnce
    storageClass: standard

ingress:
  enabled: false

resources: {}

serviceAccount:
  create: true
  name: my-service-account
  annotations:
    key1: value1
    key2: value2
  automount: true
