namespace: jenkins-namespace

jenkinsMaster:
  image: roiyki/jenkins-helm:latest
  imagePullPolicy: IfNotPresent
  services:
      jenkinsmasternodeport:
        type: NodePort
        ports:
          port: 8080
          targetport: 8080
          nodePort: 31000  # NodePort for port 8080
      jenkinsmasterclusterip:
        type: ClusterIP
        ports:
          port: 50000   # New ClusterIP port for JNLP
          targetport: 50000
  securityContext:
    runAsUser: 1000
    fsGroup: 1000
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "2"
  volumeMounts:
    - name: jenkins-home
      mountPath: /var/jenkins_home
  volumes:
    - name: jenkins-home
      persistentVolumeClaim:
        claimName: jenkins-pvc

persistence:
  enabled: true
  storageClass: "standard"  # Adjust according to your storage class
  accessMode: ReadWriteOnce
  size: 10Gi

service:
  type: NodePort
  port: 8080
  nodePort: 31000

ingress:
  enabled: false

serviceAccount:
  create: true
  name: jenkins-sa
  annotations:
    key1: value1
    key2: value2
  automount: true
