# Use Docker as a base image
FROM docker:20.10.10

# Install necessary packages (git, openssh-client, python3-pip) using apt-get
RUN apk --no-cache add git openssh-client

# Set working directory
WORKDIR /app

