name: Manual Approval Pipeline

on:
  push:
    branches:
      - main

jobs:
  manual-approval:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Wait for manual approval
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/github-script@v4
        with:
          script: |
            const { ctx, gh } = require('@actions/github'); // Renaming 'github' to 'gh'
            const { owner, repo } = ctx.repo; // Using 'ctx' instead of 'github'
            const { data: pulls } = await gh.pulls.list({ // Using 'gh' instead of 'github'
              owner,
              repo,
              state: 'open',
              head: ctx.sha
            });

            if (pulls.length > 0) {
              const prNumber = pulls[0].number;
              await gh.pulls.createReview({ // Using 'gh' instead of 'github'
                owner,
                repo,
                pull_number: prNumber,
                event: 'APPROVE'
              });
              await gh.pulls.merge({ // Using 'gh' instead of 'github'
                owner,
                repo,
                pull_number: prNumber
              });
            }

      - name: Trigger Jenkins job
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          JENKINS_SECRETS: ${{ secrets.JENKINS_SECRETS }}
        run: |
          JENKINS_USERNAME=$(echo $JENKINS_SECRETS | jq -r '.JENKINS_USERNAME')
          JENKINS_API_TOKEN=$(echo $JENKINS_SECRETS | jq -r '.JENKINS_API_TOKEN')
          curl -X POST "http://localhost:31000/job/sudokuCI2/build" \
            --user "$JENKINS_USERNAME:$JENKINS_API_TOKEN"