name: Manual Approval Pipeline

on:
  push:
    branches: [ main ]

jobs:
  manual-approval:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
    
      # Wait for manual approval
      - name: Wait for approval
        uses: jenkins-x/github-approval@v2
        with:
          approve_label: Approve
          reviewers: 'Roiyki'  # Replace with usernames or teams who can approve
    
      # Configure Git user settings
      - name: Configure Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
    
      # Verify Git user settings (optional)
      - name: Verify Git user settings
        run: |
          git config --global --get user.name
          git config --global --get user.email
    
      # Parse Jenkins secrets
      - name: Parse Jenkins secrets
        id: parse_secrets
        run: |
          echo "JENKINS_USERNAME=$(echo ${{ secrets.JENKINS_SECRETS }} | jq -r '.JENKINS_USERNAME')" >> $GITHUB_ENV
          echo "JENKINS_API_TOKEN=$(echo ${{ secrets.JENKINS_SECRETS }} | jq -r '.JENKINS_API_TOKEN')" >> $GITHUB_ENV

      # Merge feature branch into main after approval
      - name: Merge feature branch into main
        run: |
          git checkout main
          git merge feature-branch
          git push origin main
    
          # Delete feature branch locally and remotely
          git branch -d feature-branch
          git push origin --delete feature-branch
    
      # Trigger Jenkins job
      - name: Trigger Jenkins job
        uses: jenkinsci/github-actions-build@v1
        with:
          jenkins_url: 'https://localhost:31000'
          job_name: 'sudokuCI2'
          user: ${{ env.JENKINS_USERNAME }}
          token: ${{ env.JENKINS_API_TOKEN }}
