name: Manual Approval Pipeline

on:
  push:
    branches: [ main ]

jobs:
  manual-approval:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
    
      # Wait for manual approval
      - name: Wait for approval
        uses: jenkins-x/github-approval@v2
        with:
          approve_label: Approve
          reviewers: '@Roiyki'  # Replace with usernames or teams who can approve
    
      # Configure Git user settings
      - name: Configure Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
    
      # Verify Git user settings (optional)
      - name: Verify Git user settings
        run: |
          git config --global --get user.name
          git config --global --get user.email
    
      # Merge feature branch into main after approval
      - name: Merge feature branch into main
        run: |
          git checkout main
          git merge feature-branch
          git push origin main
    
          # Delete feature branch locally and remotely
          git branch -d feature-branch
          git push origin --delete feature-branch
    
      # Trigger Jenkins job
      - name: Trigger Jenkins job
        env:
          JENKINS_SECRETS: ${{ secrets.JENKINS_SECRETS }}
        run: |
          JENKINS_USERNAME=$(echo $JENKINS_SECRETS | jq -r '.JENKINS_USERNAME')
          JENKINS_API_TOKEN=$(echo $JENKINS_SECRETS | jq -r '.JENKINS_API_TOKEN')
          curl -X POST "https://localhost:31000/job/sudokuCI2/build" \
            --user "$JENKINS_USERNAME:$JENKINS_API_TOKEN"
